spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MariaDB
    username: sa
    # driver-class-name: org.h2.Driver
    password:
  jpa:
    hibernate:
      ddl-auto: create
