spring:
  output:
    ansi:
      enabled: always
  web:
    locale: ko_KR
  jpa:
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true
    hibernate:
      ddl-auto: validate
logging:
  # file:
  #   name: CodeBox.log
  level:
    # SQL
    # "[org.hibernate.SQL]": debug

    # SQL value
    # "[org.hibernate.type.descriptor.sql]": trace

    # ParamValueAOP
    "[codebox.util.aop.test.ParamValueAOP]": debug

    # TimeMeasureAOP
    "[codebox.util.aop.test.TimeMeasureAOP]": debug
